# Generated by Django 4.2.4 on 2023-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
