# Generated by Django 4.2.4 on 2023-09-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_about_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='email',
            new_name='a_email',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='a_name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='phone',
            new_name='a_phone',
        ),
    ]
