# Generated by Django 4.2.4 on 2023-09-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_email_about_a_email_rename_name_about_a_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='a_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='a_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='a_phone',
            new_name='phone',
        ),
    ]
