# Generated by Django 4.2.4 on 2023-09-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_about_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(default='Hasilpur.Punjab.Pakistan', max_length=50),
        ),
    ]
