# Generated by Django 4.2.4 on 2023-09-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='Projects',
        ),
    ]
