# Generated by Django 4.2.4 on 2023-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cv_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
